# see http://about.travis-ci.org/docs/user/languages/php/ for more hints

# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer require satooshi/php-coveralls:~1.0.0@stable
  - mkdir -p build/logs

# Commands you want to run that will verify your build.
script:
  - phpunit --configuration phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_change: always
