# see http://about.travis-ci.org/docs/user/languages/php/ for more hints

# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

# Commands to be run before your environment runs.
before_script:
  - composer require codeclimate/php-test-reporter --dev
  - composer install

# Commands you want to run that will verify your build.
script:
  - phpunit --testsuite=unit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN="0b2dc3268a070dea8e133104923d7bf9ced48daf35c79d4337f30dc1ca11f29d" vendor/bin/test-reporter --stdout > codeclimate.json
  - "sh -c 'if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then curl -X POST -d @codeclimate.json -H \"Content-Type: application/json\" -H \"User-Agent: Code Climate (PHP Test Reporter v0.1.1)\" https://codeclimate.com/test_reports  ; fi'"

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_change: always
